import {
  BarChart2, BarChart, LineChart, TrendingUp, TrendingDown,
  Phone, PhoneCall, Headphones, PhoneOff,
  ShoppingCart, Package, CreditCard, Tag,
  Users, UserX, UserCheck,
  Clock, Timer, Zap,
  Star, Target, Award,
  Shield, AlertCircle, CheckCircle,
  Ban, ThumbsUp, Smile,
  ArrowRightLeft, PauseCircle, WifiOff, ClipboardCheck,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

export const ICON_MAP: Record<string, LucideIcon> = {
  BarChart2,
  BarChart,
  LineChart,
  TrendingUp,
  TrendingDown,
  Phone,
  PhoneCall,
  PhoneOff,
  Headphones,
  ShoppingCart,
  Package,
  CreditCard,
  Tag,
  Users,
  UserX,
  UserCheck,
  Clock,
  Timer,
  Zap,
  Star,
  Target,
  Award,
  Shield,
  AlertCircle,
  CheckCircle,
  Ban,
  ThumbsUp,
  Smile,
  ArrowRightLeft,
  PauseCircle,
  WifiOff,
  ClipboardCheck,
}

export const ICON_NAMES = Object.keys(ICON_MAP) as (keyof typeof ICON_MAP)[]
